project:
  type: website

website:
  title: "PhDemetri"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Dpananos
      - icon: twitter
        href: https://twitter.com/PhDemetri
      - icon: linkedin
        href: https://www.linkedin.com/in/demetripananos/
format:
  html:
    theme: flatly
    css: styles.css



